version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/app/Backend
      - /app/Backend/node_modules
    ports:
      - "3000:3000"
    command: "npx nodemon /app/Backend/server.js"
    environment:
      NODE_ENV: development
    depends_on:
      - database

  database:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: